# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Anowindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AnoWindow(object):
    def setupUi(self, AnoWindow):
        AnoWindow.setObjectName("AnoWindow")
        AnoWindow.resize(1922, 1067)
        AnoWindow.setTabletTracking(False)
        AnoWindow.setAutoFillBackground(False)
        AnoWindow.setStyleSheet("")
        AnoWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(AnoWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.greenButton = QtWidgets.QPushButton(self.centralwidget)
        self.greenButton.setGeometry(QtCore.QRect(1280, 180, 435, 360))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.greenButton.setFont(font)
        self.greenButton.setStyleSheet("background-color: rgb(2, 2, 91); \n"
"color: white;\n"
"border-radius: 100px;  border: 2px groove gray;\n"
"border-style: outset;")
        self.greenButton.setText("")
        self.greenButton.setObjectName("greenButton")
        self.redButton = QtWidgets.QPushButton(self.centralwidget)
        self.redButton.setGeometry(QtCore.QRect(140, 180, 435, 360))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.redButton.setFont(font)
        self.redButton.setStyleSheet("background-color: rgb(2, 2, 91); \n"
"color: white;\n"
"border-radius: 105px;  border: 2px groove gray;\n"
"border-style: outset;")
        self.redButton.setText("")
        self.redButton.setObjectName("redButton")
        self.exitbutton = QtWidgets.QPushButton(self.centralwidget)
        self.exitbutton.setGeometry(QtCore.QRect(1740, 10, 145, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.exitbutton.setFont(font)
        self.exitbutton.setText("")
        self.exitbutton.setObjectName("exitbutton")
        self.tempButton = QtWidgets.QPushButton(self.centralwidget)
        self.tempButton.setGeometry(QtCore.QRect(1280, 650, 435, 360))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.tempButton.setFont(font)
        self.tempButton.setStyleSheet("background-color: rgb(2, 2, 91); \n"
"color: white;\n"
"border-radius: 100px;  border: 2px groove gray;\n"
"border-style: outset;")
        self.tempButton.setText("")
        self.tempButton.setObjectName("tempButton")
        self.dateLable = QtWidgets.QLabel(self.centralwidget)
        self.dateLable.setGeometry(QtCore.QRect(1260, 0, 471, 110))
        self.dateLable.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dateLable.setStyleSheet("")
        self.dateLable.setText("")
        self.dateLable.setTextFormat(QtCore.Qt.RichText)
        self.dateLable.setAlignment(QtCore.Qt.AlignCenter)
        self.dateLable.setObjectName("dateLable")
        self.backgroundlable = QtWidgets.QLabel(self.centralwidget)
        self.backgroundlable.setGeometry(QtCore.QRect(0, -10, 1920, 1080))
        self.backgroundlable.setAutoFillBackground(True)
        self.backgroundlable.setText("")
        self.backgroundlable.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.backgroundlable.setObjectName("backgroundlable")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setText("")
        self.label.setObjectName("label")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(0, 1080, 1920, 10))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.School = QtWidgets.QLabel(self.centralwidget)
        self.School.setGeometry(QtCore.QRect(20, 20, 211, 80))
        self.School.setText("")
        self.School.setObjectName("School")
        self.ShowIPLabel = QtWidgets.QLabel(self.centralwidget)
        self.ShowIPLabel.setGeometry(QtCore.QRect(1720, 1020, 200, 60))
        self.ShowIPLabel.setText("")
        self.ShowIPLabel.setObjectName("ShowIPLabel")
        self.yellowButton = QtWidgets.QPushButton(self.centralwidget)
        self.yellowButton.setGeometry(QtCore.QRect(710, 180, 435, 360))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.yellowButton.setFont(font)
        self.yellowButton.setStyleSheet("background-color: rgb(2, 2, 91); \n"
"color: white;\n"
"border-radius: 105px;  border: 2px groove gray;\n"
"border-style: outset;")
        self.yellowButton.setText("")
        self.yellowButton.setObjectName("yellowButton")
        self.fingerButton = QtWidgets.QPushButton(self.centralwidget)
        self.fingerButton.setGeometry(QtCore.QRect(710, 650, 435, 360))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.fingerButton.setFont(font)
        self.fingerButton.setStyleSheet("background-color: rgb(2, 2, 91); \n"
"color: white;\n"
"border-radius: 105px;  border: 2px groove gray;\n"
"border-style: outset;")
        self.fingerButton.setText("")
        self.fingerButton.setObjectName("fingerButton")
        self.fanButton = QtWidgets.QPushButton(self.centralwidget)
        self.fanButton.setGeometry(QtCore.QRect(140, 650, 435, 360))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.fanButton.setFont(font)
        self.fanButton.setStyleSheet("background-color: rgb(2, 2, 91); \n"
"color: white;\n"
"border-radius: 105px;  border: 2px groove gray;\n"
"border-style: outset;")
        self.fanButton.setText("")
        self.fanButton.setObjectName("fanButton")
        self.label.raise_()
        self.backgroundlable.raise_()
        self.dateLable.raise_()
        self.redButton.raise_()
        self.tempButton.raise_()
        self.greenButton.raise_()
        self.exitbutton.raise_()
        self.line_6.raise_()
        self.School.raise_()
        self.ShowIPLabel.raise_()
        self.yellowButton.raise_()
        self.fingerButton.raise_()
        self.fanButton.raise_()
        AnoWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(AnoWindow)
        QtCore.QMetaObject.connectSlotsByName(AnoWindow)

    def retranslateUi(self, AnoWindow):
        _translate = QtCore.QCoreApplication.translate
        AnoWindow.setWindowTitle(_translate("AnoWindow", "MainWindow"))
