# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        MainWindow.setTabletTracking(False)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # 1上
        self.showlocationbutton = QtWidgets.QPushButton(self.centralwidget)
        self.showlocationbutton.setGeometry(QtCore.QRect(30, 180, 435, 360))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.showlocationbutton.setFont(font)
        self.showlocationbutton.setStyleSheet("background-color: rgb(2, 2, 91); \n"
"color: white;\n"
"border-radius: 105px;  border: 2px groove gray;\n"
"border-style: outset;")
        self.showlocationbutton.setText("")
        self.showlocationbutton.setObjectName("showlocationbutton")

        # 1下
        self.showperiodbutton = QtWidgets.QPushButton(self.centralwidget)
        self.showperiodbutton.setGeometry(QtCore.QRect(30, 650, 435, 360))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.showperiodbutton.setFont(font)
        self.showperiodbutton.setStyleSheet("background-color: rgb(2, 2, 91); \n"
                                            "color: white;\n"
                                            "border-radius: 100px;  border: 2px groove gray;\n"
                                            "border-style: outset;")
        self.showperiodbutton.setText("")
        self.showperiodbutton.setObjectName("showperiodbutton")

        # 2上
        self.showvoice = QtWidgets.QPushButton(self.centralwidget)
        self.showvoice.setGeometry(QtCore.QRect(510, 180, 435, 360))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.showvoice.setFont(font)
        self.showvoice.setStyleSheet("background-color: rgb(2, 2, 91); \n"
                                     "color: white;\n"
                                     "border-radius: 105px;  border: 2px groove gray;\n"
                                     "border-style: outset;")
        self.showvoice.setText("")
        self.showvoice.setObjectName("showvoice")

        # 2下
        self.showdeepseek = QtWidgets.QPushButton(self.centralwidget)
        self.showdeepseek.setGeometry(QtCore.QRect(510, 650, 435, 360))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.showdeepseek.setFont(font)
        self.showdeepseek.setStyleSheet("background-color: rgb(2, 2, 91); \n"
                                        "color: white;\n"
                                        "border-radius: 105px;  border: 2px groove gray;\n"
                                        "border-style: outset;")
        self.showdeepseek.setText("")
        self.showdeepseek.setObjectName("showdeepseek")

        # 3上
        self.showvirusbutton = QtWidgets.QPushButton(self.centralwidget)
        self.showvirusbutton.setGeometry(QtCore.QRect(990, 180, 435, 360))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.showvirusbutton.setFont(font)
        self.showvirusbutton.setStyleSheet("background-color: rgb(2, 2, 91); \n"
                                           "color: white;\n"
                                           "border-radius: 100px;  border: 2px groove gray;\n"
                                           "border-style: outset;")
        self.showvirusbutton.setText("")
        self.showvirusbutton.setObjectName("showvirusbutton")

        # 3下
        self.showpestsbutton = QtWidgets.QPushButton(self.centralwidget)
        self.showpestsbutton.setGeometry(QtCore.QRect(990, 650, 435, 360))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.showpestsbutton.setFont(font)
        self.showpestsbutton.setStyleSheet("background-color: rgb(2, 2, 91); \n"
                                           "color: white;\n"
                                           "border-radius: 100px;  border: 2px groove gray;\n"
                                           "border-style: outset;")
        self.showpestsbutton.setText("")
        self.showpestsbutton.setObjectName("showpestsbutton")

        # 4上
        self.newButton1 = QtWidgets.QPushButton(self.centralwidget)
        self.newButton1.setGeometry(QtCore.QRect(1470, 180, 435, 360))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.newButton1.setFont(font)
        self.newButton1.setStyleSheet("background-color: rgb(2, 2, 91); \n"
                                      "color: white;\n"
                                      "border-radius: 105px;  border: 2px groove gray;\n"
                                      "border-style: outset;")
        self.newButton1.setText("")
        self.newButton1.setObjectName("newButton1")

        # 4下
        self.newButton2 = QtWidgets.QPushButton(self.centralwidget)
        self.newButton2.setGeometry(QtCore.QRect(1470, 650, 435, 360))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.newButton2.setFont(font)
        self.newButton2.setStyleSheet("background-color: rgb(2, 2, 91); \n"
                                      "color: white;\n"
                                      "border-radius: 105px;  border: 2px groove gray;\n"
                                      "border-style: outset;")
        self.newButton2.setText("")
        self.newButton2.setObjectName("newButton2")

        # 退出
        self.exitbutton = QtWidgets.QPushButton(self.centralwidget)
        self.exitbutton.setGeometry(QtCore.QRect(1740, 10, 145, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.exitbutton.setFont(font)
        self.exitbutton.setText("")
        self.exitbutton.setObjectName("exitbutton")



        self.dateLable = QtWidgets.QLabel(self.centralwidget)
        self.dateLable.setGeometry(QtCore.QRect(1260, 0, 471, 110))
        self.dateLable.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dateLable.setStyleSheet("")
        self.dateLable.setText("")
        self.dateLable.setTextFormat(QtCore.Qt.RichText)
        self.dateLable.setAlignment(QtCore.Qt.AlignCenter)
        self.dateLable.setObjectName("dateLable")
        self.backgroundlable = QtWidgets.QLabel(self.centralwidget)
        self.backgroundlable.setGeometry(QtCore.QRect(0, -10, 1923, 1083))
        self.backgroundlable.setAutoFillBackground(True)
        self.backgroundlable.setText("")
        self.backgroundlable.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.backgroundlable.setObjectName("backgroundlable")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setText("")
        self.label.setObjectName("label")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(0, 1080, 1920, 10))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.School = QtWidgets.QLabel(self.centralwidget)
        self.School.setGeometry(QtCore.QRect(20, 20, 211, 80))
        self.School.setText("")
        self.School.setObjectName("School")
        self.ShowIPLabel = QtWidgets.QLabel(self.centralwidget)
        self.ShowIPLabel.setGeometry(QtCore.QRect(1720, 1020, 200, 60))
        self.ShowIPLabel.setText("")
        self.ShowIPLabel.setObjectName("ShowIPLabel")

        self.label.raise_()
        self.backgroundlable.raise_()
        self.dateLable.raise_()
        self.showlocationbutton.raise_()
        self.showperiodbutton.raise_()
        self.showpestsbutton.raise_()
        self.showvirusbutton.raise_()
        self.exitbutton.raise_()
        self.line_6.raise_()
        self.School.raise_()
        self.ShowIPLabel.raise_()
        self.showdeepseek.raise_()
        self.showvoice.raise_()
        self.newButton1.raise_()
        self.newButton2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
